#!/bin/bash

echo "Installing brew"
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

echo "Installing iTerm"
brew cask install iterm2

echo "Installing FZF with dependencies"
brew install fzf
$(brew --prefix)/opt/fzf/install
brew install bat
brew install the_silver_searcher

echo "Copying config files"
cp .vimrc ~/.vimrc
cp .bash_profile ~/.bash_profile
cp .ackrc ~/.ackrc

echo "Setting vim global-ignore"
cp .gitignore_global ~/.gitignore_global
git config --global core.excludesfile ~/.gitignore_global

echo "Installing ZSH Touchbar plugin"
cd ${ZSH_CUSTOM1:-$ZSH/custom}/plugins
git clone https://github.com/kamilsdz/zsh-iterm-touchbar.git

echo "Installing Pathogen"
mkdir -p ~/.vim/autoload ~/.vim/bundle && curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

echo "Cloning vim plugins"
cd ~/.vim/bundle
git clone https://github.com/mileszs/ack.vim
git clone https://github.com/wincent/command-t
git clone https://github.com/ekalinin/dockerfile.vim
git clone https://github.com/morhetz/gruvbox
git clone https://github.com/scrooloose/nerdtree
git clone https://github.com/andrewradev/splitjoin.vim
git clone https://github.com/mbbill/undotree
git clone https://github.com/djoshea/vim-autoread
git clone https://github.com/ntpeters/vim-better-whitespace
git clone https://github.com/misterbuckley/vim-definitive
git clone https://github.com/tpope/vim-fugitive
git clone https://github.com/airblade/vim-gitgutter
git clone https://github.com/pangloss/vim-javascript
git clone https://github.com/terryma/vim-multiple-cursors
git clone https://github.com/tpope/vim-rails
git clone https://github.com/ecomba/vim-ruby-refactoring
git clone https://github.com/vim-ruby/vim-ruby
git clone https://github.com/tpope/vim-surround
git clone https://github.com/thaerkh/vim-workspace
git clone https://github.com/junegunn/fzf.vim
git clone https://github.com/junegunn/fzf

echo "Installing 3rd party vim plugins"
brew install ack

echo "Installing Oh My Zsh"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
cp .zshrc ~/.zshrc
